In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

%matplotlib inline

In [2]:
arr = [6,7,8]
print(type(arr))

<class 'list'>


In [3]:
a = np.array(arr)
print(type(a))
print(a.shape)
print(a.dtype)
print(a.ndim)

<class 'numpy.ndarray'>
(3,)
int32
1


In [4]:
b = np.array([[1,2,3], [4,5,6]])
print(b.ndim)
print(b.shape)

2
(2, 3)


In [6]:
np.random.random((2,3))
np.zeros((2,3))
np.identity((3))
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
c = np.array([[9.0, 8.0, 7.0], [1.0, 4.0, 6.0]])
d = np.array([[14.0, 15.0, 13.0], [25.0, 45.0, 35.0]])

In [7]:
print(c+d)
print(c*d)
print(5/d)
print(c**2)

[[23. 23. 20.]
 [26. 49. 41.]]
[[126. 120.  91.]
 [ 25. 180. 210.]]
[[0.35714286 0.33333333 0.38461538]
 [0.2        0.11111111 0.14285714]]
[[81. 64. 49.]
 [ 1. 16. 36.]]


In [8]:
print(a[0])
print(a[2])
print(b[0,0])
print(b[1,2])
print(c[0,1])
print(c[1,0])
print(d[1, 0:2])

6
8
1
6
8.0
1.0
[25. 45.]


In [9]:
e = np.array([[10,11,12],[13,14,15],
              [16,17,18],[19,20,21]])
print(e[:3, :2])

[[10 11]
 [13 14]
 [16 17]]


In [10]:
print(e[e>15])
print(e[[2,0,3,1], [2,1,0,2]])

[16 17 18 19 20 21]
[18 11 19 15]


In [11]:
fuel_info = pd.read_csv('http://bit.ly/HDSC-Dataset')

In [12]:
fuel_info


record_id  utility_id_ferc1  report_year  \
0        f1_fuel_1994_12_1_0_7                 1         1994   
1       f1_fuel_1994_12_1_0_10                 1         1994   
2        f1_fuel_1994_12_2_0_1                 2         1994   
3        f1_fuel_1994_12_2_0_7                 2         1994   
4       f1_fuel_1994_12_2_0_10                 2         1994   
...                        ...               ...          ...   
29518  f1_fuel_2018_12_12_0_13                12         2018   
29519   f1_fuel_2018_12_12_1_1                12         2018   
29520  f1_fuel_2018_12_12_1_10                12         2018   
29521  f1_fuel_2018_12_12_1_13                12         2018   
29522  f1_fuel_2018_12_12_1_14                12         2018   

           plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0                  rockport                coal       ton        5377489.0   
1      rockport total plant                coal       ton       10486945.0   
2                    gorgas                coal       ton        2978683.0   
3                     barry                coal       ton        3739484.0   
4                 chickasaw                 gas       mcf          40533.0   
...                     ...                 ...       ...              ...   
29518    neil simpson ct #1                 gas       mcf          18799.0   
29519  cheyenne prairie 58%                 gas       mcf         806730.0   
29520     lange ct facility                 gas       mcf         104554.0   
29521       wygen 3 bhp 52%                coal       ton         315945.0   
29522       wygen 3 bhp 52%                 gas       mcf          17853.0   

       fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0                   16.590                      18.59   
1                   16.592                      18.58   
2                   24.130                      39.72   
3                   23.950                      47.21   
4                    1.000                       2.77   
...                    ...                        ...   
29518                1.059                       4.78   
29519                1.050                       3.65   
29520                1.060                       4.77   
29521               16.108                       3.06   
29522                1.059                       0.00   

       fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                             18.53                1.121  
1                             18.53                1.120  
2                             38.12                1.650  
3                             45.99                1.970  
4                              2.77                2.570  
...                             ...                  ...  
29518                          4.78                9.030  
29519                          3.65                6.950  
29520                          4.77                8.990  
29521                         14.76                1.110  
29522                          0.00               11.680  

[29523 rows x 11 columns]

In [13]:
fuel_info.describe()

utility_id_ferc1   report_year  fuel_qty_burned  fuel_mmbtu_per_unit  \
count      29523.000000  29523.000000     2.952300e+04         29523.000000   
mean         118.601836   2005.806050     2.622119e+06             8.492111   
std           74.178353      7.025483     9.118004e+06            10.600220   
min            1.000000   1994.000000     1.000000e+00             0.000001   
25%           55.000000   2000.000000     1.381700e+04             1.024000   
50%          122.000000   2006.000000     2.533220e+05             5.762694   
75%          176.000000   2012.000000     1.424034e+06            17.006000   
max          514.000000   2018.000000     5.558942e+08           341.260000   

       fuel_cost_per_unit_burned  fuel_cost_per_unit_delivered  \
count               29523.000000                  2.952300e+04   
mean                  208.649031                  9.175704e+02   
std                  2854.490090                  6.877593e+04   
min                  -276.080000                 -8.749370e+02   
25%                     5.207000                  3.778500e+00   
50%                    26.000000                  1.737100e+01   
75%                    47.113000                  4.213700e+01   
max                139358.000000                  7.964521e+06   

       fuel_cost_per_mmbtu  
count         29523.000000  
mean             19.304354  
std            2091.540939  
min             -41.501000  
25%               1.940000  
50%               4.127000  
75%               7.745000  
max          359278.000000

In [14]:
### Question 3
fuel_info.groupby("fuel_type_code_pudl")["fuel_cost_per_unit_burned"].mean().sort_values()

fuel_type_code_pudl
gas          13.659397
other        18.253856
waste        19.518122
coal         67.421830
oil         168.877086
nuclear    4955.157002
Name: fuel_cost_per_unit_burned, dtype: float64

In [17]:
fuel_info.shape

(29523, 11)

In [18]:
### Question 4

fuel_info.describe()["fuel_mmbtu_per_unit"]

count    29523.000000
mean         8.492111
std         10.600220
min          0.000001
25%          1.024000
50%          5.762694
75%         17.006000
max        341.260000
Name: fuel_mmbtu_per_unit, dtype: float64

In [19]:
### Question 5

fuel_info["fuel_qty_burned"].skew()

15.851495469109503

In [20]:
fuel_info["fuel_qty_burned"].kurt()

651.3694501337732

In [21]:
### Question 6

fuel_info.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [22]:
### Dividing the whole data set with the first column to the fracction.

fuel_info.isnull().sum()/fuel_info.shape[0]

record_id                       0.000000
utility_id_ferc1                0.000000
report_year                     0.000000
plant_name_ferc1                0.000000
fuel_type_code_pudl             0.000000
fuel_unit                       0.006097
fuel_qty_burned                 0.000000
fuel_mmbtu_per_unit             0.000000
fuel_cost_per_unit_burned       0.000000
fuel_cost_per_unit_delivered    0.000000
fuel_cost_per_mmbtu             0.000000
dtype: float64

In [23]:
### Multiplying the fractional output with 100 to convert it to percentage
fuel_info.isnull().sum()/fuel_info.shape[0]*100

record_id                       0.000000
utility_id_ferc1                0.000000
report_year                     0.000000
plant_name_ferc1                0.000000
fuel_type_code_pudl             0.000000
fuel_unit                       0.609694
fuel_qty_burned                 0.000000
fuel_mmbtu_per_unit             0.000000
fuel_cost_per_unit_burned       0.000000
fuel_cost_per_unit_delivered    0.000000
fuel_cost_per_mmbtu             0.000000
dtype: float64

In [24]:
### Question 7

fuel_info.groupby( 'fuel_unit' )[ 'fuel_unit' ].count()
fuel_info[[ 'fuel_unit' ]] = fuel_info[[ 'fuel_unit' ]].fillna(value= 'mcf' )

In [25]:
### print out the information of the Dtype

fuel_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29523 entries, 0 to 29522
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   record_id                     29523 non-null  object 
 1   utility_id_ferc1              29523 non-null  int64  
 2   report_year                   29523 non-null  int64  
 3   plant_name_ferc1              29523 non-null  object 
 4   fuel_type_code_pudl           29523 non-null  object 
 5   fuel_unit                     29523 non-null  object 
 6   fuel_qty_burned               29523 non-null  float64
 7   fuel_mmbtu_per_unit           29523 non-null  float64
 8   fuel_cost_per_unit_burned     29523 non-null  float64
 9   fuel_cost_per_unit_delivered  29523 non-null  float64
 10  fuel_cost_per_mmbtu           29523 non-null  float64
dtypes: float64(5), int64(2), object(4)
memory usage: 2.5+ MB


In [26]:
### Question 8

fuel_info.corr()["fuel_cost_per_unit_burned"].sort_values(ascending = False).tail(3)

fuel_mmbtu_per_unit   -0.010034
fuel_qty_burned       -0.018535
utility_id_ferc1      -0.037863
Name: fuel_cost_per_unit_burned, dtype: float64

In [27]:
### Question 9

coal_info = fuel_info.loc[fuel_info["fuel_type_code_pudl"]== "coal"]

In [28]:
special_year = coal_info.groupby("report_year")["fuel_cost_per_unit_burned"].sum().loc[[1998, 1994]]
special_year

report_year
1998    11902.597
1994    14984.572
Name: fuel_cost_per_unit_burned, dtype: float64

In [29]:
sum_total = special_year.sum()

In [30]:
special_year/sum_total

report_year
1998    0.442687
1994    0.557313
Name: fuel_cost_per_unit_burned, dtype: float64

In [31]:
((0.442687-0.557313)/0.557313)*100

-20.567616402273043

In [32]:
### Question 10

fuel_info.groupby("report_year")["fuel_cost_per_unit_delivered"].sum().sort_values(ascending = False)

report_year
1997    1.218738e+07
1996    1.000602e+07
2000    1.352903e+06
2009    7.975923e+05
2018    4.748057e+05
2015    3.569033e+05
1998    3.178799e+05
2014    2.256952e+05
2013    2.065968e+05
2004    1.663129e+05
2010    1.158381e+05
2016    1.074344e+05
2001    8.142834e+04
1994    7.859053e+04
2012    7.581617e+04
2011    7.412059e+04
2008    7.194631e+04
2003    6.740849e+04
2002    5.735121e+04
2007    5.476283e+04
2005    5.258506e+04
2006    4.805125e+04
2017    4.587348e+04
1995    3.931506e+04
1999    2.682921e+04
Name: fuel_cost_per_unit_delivered, dtype: float64

# THANK YOU 